use crate::core::McfProject;
use std::fs::File;
use std::io::Write;

pub fn write(project: &McfProject, output_path: &str) -> Result<(), std::io::Error> {
    let mut file = File::create(output_path)?;

    writeln!(file, "# MCF v0.3 | Generated by Rust Engine")?;
    writeln!(file, "project: \"{}\"", project.title)?;
    writeln!(file, "bpm: {:.1}", project.bpm)?;
    writeln!(file, "key: \"C\"")?;
    writeln!(file, "scale: \"Major\"\n")?;

    writeln!(file, "# TRACKS [id, name, type, volume, pan]")?;
    writeln!(file, "tr:")?;
    for track in &project.tracks {
        writeln!(
            file,
            "{}, \"{}\", {}, {:.2}, {:.2}",
            track.id, track.name, track.track_type, track.volume, track.pan
        )?;
    }
    
    writeln!(file, "\n# NOTES [track, note, velocity, start, duration]")?;
    writeln!(file, "nt:")?;
    for note in &project.notes {
        writeln!(
            file,
            "{}, {}, {}, {:.2}, {:.2}",
            note.track_id, note.pitch_name, note.velocity, note.start, note.duration
        )?;
    }

    Ok(())
}